# Generated by Django 4.2.6 on 2023-11-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, default='anime_images/empty.svg', upload_to='anime_images/'),
        ),
    ]
