# Generated by Django 4.2.6 on 2023-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0003_anime_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
