# Generated by Django 4.2.6 on 2023-11-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_catalog.profile'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('items', models.ManyToManyField(to='anime_catalog.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_catalog.profile')),
            ],
        ),
    ]
