# Generated by Django 4.2.6 on 2023-11-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0007_alter_rating_for_user_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='for_anime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime_catalog.anime'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='for_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime_catalog.profile'),
        ),
    ]
