# Generated by Django 4.2.6 on 2023-11-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0008_alter_rating_for_anime_alter_rating_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
