# Generated by Django 4.2.6 on 2023-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=12, max_length=64),
            preserve_default=False,
        ),
    ]
