# Generated by Django 4.2.6 on 2023-11-09 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(150)]),
        ),
    ]
