from django.urls import path
from . import views


urlpatterns = [
    path('short-anime/', views.ShortAnimeListAPIView.as_view()),
    path('full-anime/', views.FullAnimeListAPIView.as_view()),
    path('anime-create/', views.AnimeCreateAPIView.as_view()),
    path('anime-update/<int:pk>/', views.AnimeUpdateAPIView.as_view()),
    path('anime-delete/<int:pk>/', views.AnimeDeleteAPIView.as_view()),
    path('anime-retrieve/<int:pk>/', views.AnimeRetrieveAPIView.as_view()),
    path('anime-retrieve/<int:pk>/average-rating/', views.AnimeAverageRatingView.as_view()),
    path('anime-retrieve/<int:pk>/rating-count/', views.AnimeRatingDistributionView.as_view()),
    path('genre-list/', views.GenreListAPIView.as_view()),
    path('genre-retrieve/<int:pk>/', views.GenreRetrieveAPIView.as_view()),
    path('genre-create/', views.GenreCreateAPIView.as_view()),
    path('genre-update/<int:pk>/', views.GenreUpdateAPIView.as_view()),
    path('genre-delete/<int:pk>/', views.GenreDeleteAPIView.as_view()),
    path('studio-list/', views.StudioListAPIView.as_view()),
    path('studio-create/', views.StudioCreateAPIView.as_view()),
    path('studio-update/<int:pk>/', views.StudioUpdateAPIView.as_view()),
    path('studio-delete/<int:pk>/', views.StudioDeleteAPIView.as_view()),
    path('rating-create/', views.RatingCreateAPIView.as_view()),
    path('rating-update/<int:pk>/', views.RatingUpdateAPIView.as_view()),
    path('rating-delete/<int:pk>/', views.RatingDeleteAPIView.as_view()),
    path('collection-list/', views.CollectionListAPIView.as_view()),
    path('collection-create/', views.CollectionCreateAPIView.as_view()),
    path('collection-update/<int:pk>/', views.CollectionUpdateAPIView.as_view()),
    path('collection-delete/<int:pk>/', views.CollectionDeleteAPIView.as_view()),
    path('comment-list/', views.CommentListAPIView.as_view()),
    path('comment-retrieve/<int:pk>/', views.CommentRetrieveAPIView.as_view()),
    path('comment-create/', views.CommentCreateAPIView.as_view()),
    path('comment-update/<int:pk>/', views.CommentUpdateAPIView.as_view()),
    path('comment-delete/<int:pk>/', views.CommentDeleteAPIView.as_view()),
    path('review-list/', views.ReviewListAPIView.as_view()),
    path('review-retrieve/<int:pk>/', views.ReviewRetrieveAPIView.as_view()),
    path('review-create/', views.ReviewCreateAPIView.as_view()),
    path('review-update/<int:pk>/', views.ReviewUpdateAPIView.as_view()),
    path('review-delete/<int:pk>/', views.ReviewDeleteAPIView.as_view()),
    path('register/', views.UserRegistrationView.as_view()),
]

