from django.urls import path
from . import views


urlpatterns = [
    path('short-anime/', views.ShortAnimeListAPIView.as_view(), name='short-anime-list'),
    path('full-anime/', views.FullAnimeListAPIView.as_view(), name='full-anime-list'),
    path('anime-create/', views.AnimeCreateAPIView.as_view(), name='anime-create'),
    path('anime-update/<int:pk>/', views.AnimeUpdateAPIView.as_view(), name='anime-update'),
    path('anime-delete/<int:pk>/', views.AnimeDeleteAPIView.as_view(), name='anime-delete'),
    path('anime-retrieve/<int:pk>/', views.AnimeRetrieveAPIView.as_view(), name='anime-retrieve'),
    path('anime-retrieve/<int:pk>/average-rating/', views.AnimeAverageRatingView.as_view(), name='anime-average-rating'),
    path('anime-retrieve/<int:pk>/rating-count/', views.AnimeRatingDistributionView.as_view(), name='anime-rating-distribution'),
    path('genre-list/', views.GenreListAPIView.as_view(), name='genre-list'),
    path('genre-retrieve/<int:pk>/', views.GenreRetrieveAPIView.as_view(), name='genre-retrieve'),
    path('genre-create/', views.GenreCreateAPIView.as_view(), name='genre-create'),
    path('genre-update/<int:pk>/', views.GenreUpdateAPIView.as_view(), name='genre-update'),
    path('genre-delete/<int:pk>/', views.GenreDeleteAPIView.as_view(), name='genre-delete'),
    path('studio-list/', views.StudioListAPIView.as_view(), name='studio-list'),
    path('studio-create/', views.StudioCreateAPIView.as_view(), name='studio-create'),
    path('studio-update/<int:pk>/', views.StudioUpdateAPIView.as_view(), name='studio-update'),
    path('studio-delete/<int:pk>/', views.StudioDeleteAPIView.as_view(), name='studio-delete'),
    path('rating-create/', views.RatingCreateAPIView.as_view(), name='rating-create'),
    path('rating-update/<int:pk>/', views.RatingUpdateAPIView.as_view(), name='rating-update'),
    path('rating-delete/<int:pk>/', views.RatingDeleteAPIView.as_view(), name='rating-delete'),
    path('collection-list/', views.CollectionListAPIView.as_view(), name='collection-list'),
    path('collection-create/', views.CollectionCreateAPIView.as_view(), name='collection-create'),
    path('collection-update/<int:pk>/', views.CollectionUpdateAPIView.as_view(), name='collection-update'),
    path('collection-delete/<int:pk>/', views.CollectionDeleteAPIView.as_view(), name='collection-delete'),
    path('comment-list/', views.CommentListAPIView.as_view(), name='comment-list'),
    path('comment-retrieve/<int:pk>/', views.CommentRetrieveAPIView.as_view(), name='comment-detail'),
    path('comment-create/', views.CommentCreateAPIView.as_view(), name='comment-create'),
    path('comment-update/<int:pk>/', views.CommentUpdateAPIView.as_view(), name='comment-update'),
    path('comment-delete/<int:pk>/', views.CommentDeleteAPIView.as_view(), name='comment-delete'),
    path('review-list/', views.ReviewListAPIView.as_view(), name='review-list'),
    path('review-retrieve/<int:pk>/', views.ReviewRetrieveAPIView.as_view(), name='review-retrieve'),
    path('review-create/', views.ReviewCreateAPIView.as_view(), name='review-create'),
    path('review-update/<int:pk>/', views.ReviewUpdateAPIView.as_view(), name='review-update'),
    path('review-delete/<int:pk>/', views.ReviewDeleteAPIView.as_view(), name='review-delete'),
    path('register/', views.UserRegistrationView.as_view(), name='user-registration'),
]
